spring:
  datasource:
    url: jdbc:oracle:thin:@172.20.2.39:1521/SBIS
    username: dbamv
    password: SBIS2023
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    properties:
      hibernate:
        show_sql: true
  h2:
    console:
      enabled: true

spring-doc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
