version: "3.7"

services:
  app:
    build: .
    volumes:
      - ../:/home/app/cds-ph-tasy/:rw
    depends_on:
      - mysql
      - mongo

  mongo:
    image: mongo:4.2
    hostname: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
    restart: always
    env_file:
      - mysql.env
    ports:
      - "3306:3306"
